// Package provision writes Action URL settings to phones, either as a
// Grandstream XML provisioning file or live over the phone's SSH CLI.
package provision

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"io"
	"strings"

	"github.com/shambles07/grandstream-actionurl-server/internal/actionurl"
)

// WriteXML writes a Grandstream gs_provision config file containing the given
// settings. With FormatPCode it emits <config version="1"> with <Pnnnn>
// elements; with FormatAlias it emits <config version="2"> with
// <item name="..."> elements. mac is optional; when set it is included so the
// phone rejects a file meant for a different device.
func WriteXML(w io.Writer, f actionurl.Format, mac string, settings []actionurl.Setting) error {
	var b bytes.Buffer
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString("<!-- Grandstream Action URL settings generated by gsprov -->\n")
	b.WriteString(`<gs_provision version="1">` + "\n")
	if mac != "" {
		b.WriteString("  <mac>")
		xml.EscapeText(&b, []byte(mac))
		b.WriteString("</mac>\n")
	}
	version := "1"
	if f == actionurl.FormatAlias {
		version = "2"
	}
	fmt.Fprintf(&b, "  <config version=%q>\n", version)
	for _, s := range settings {
		fmt.Fprintf(&b, "    <!-- %s (web UI: %s) -->\n", commentSafe(s.Event.Name), commentSafe(s.Event.WebUIName))
		if f == actionurl.FormatAlias {
			b.WriteString(`    <item name="`)
			xml.EscapeText(&b, []byte(s.Key))
			b.WriteString(`">`)
			xml.EscapeText(&b, []byte(s.Value))
			b.WriteString("</item>\n")
		} else {
			fmt.Fprintf(&b, "    <%s>", s.Key)
			xml.EscapeText(&b, []byte(s.Value))
			fmt.Fprintf(&b, "</%s>\n", s.Key)
		}
	}
	b.WriteString("  </config>\n</gs_provision>\n")
	_, err := w.Write(b.Bytes())
	return err
}

func commentSafe(s string) string { return strings.ReplaceAll(s, "--", "- -") }

// ConfigFileName returns the conventional provisioning file name for a phone
// (cfg<mac>.xml), or "cfg.xml" when mac is empty.
func ConfigFileName(mac string) string {
	return "cfg" + mac + ".xml"
}
